# Welcome to Jekyll!

# Site variables -------
title: chabudai
email: nathanteetor@gmail.com
description: A table plugin for Bootstrap 4
baseurl: /chabudai
url: https://nteetor.github.io/

# Build settings -------
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Excluded files -------
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md